---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-xml
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: fix-byte-order-marker  # Forbid UTF-8 byte-order markers
  - repo: https://github.com/pocc/pre-commit-hooks.git
    rev: v1.3.5
    hooks:
      - id: clang-format
      - id: clang-tidy
        args:
        - --version=19
